
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE =postgres
      - SPRING_DATASOURCE_URL =jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME =postgres
      - SPRING_DATASOURCE_PASSWORD =postgres
      - SPRING_DATA_REDIS_HOST =redis-cache # caching stuff
      - SPRING_DATA_REDIS_PORT =6379
      - SPRING_CACHE_REDIS_TIME-TO-LIVE =60000
    depends_on:
      - postgres
      - redis-cache

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432" #<-base postgres port
    environment:
      - POSTGRES_USER =postgres
      - POSTGRES_PASSWORD =postgres
      - POSTGRES_DB =postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data #why?

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379" #<-base redis port
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data: