services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-db:9092/mem:testdb
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
    depends_on:
      - h2-db

  h2-db:
    image: h2:2.2.224
    command: -tcp -tcpAllowOthers -tcpPort 9092 -ifNotExists
    ports:
      - "9092:9092"  # Для подключения приложения
      - "8082:8082"  # Для веб-консоли
    #environment:
    #  - H2_OPTIONS=-tcp -tcpAllowOthers -tcpPort 9092

