services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-db:9092/mem:testdb
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
    depends_on:
      h2-db:
        condition: service_healthy


  h2-db:
    image: oscarfonts/h2
    networks:
      - app-network
    ports:
      - "8082:8082"
    healthcheck: # ← Добавлен healthcheck
      test: [ "CMD", "curl", "-f", "http://localhost:8082" ]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -tcpPort 9092

networks:  # Определяем сеть
  app-network:
    driver: bridge