
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      #jdbc:postgresql://[host]:[port]/[database_name?]
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432" #<-base postgres port
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data #why?
volumes:
  postgres-data: